/**
 * Single source of truth for the whole platform (web, Telegram bot, Bale bot, admin panels).
 *
 * Multi-tenancy: every business table carries `tenant_id`. Application code must always
 * query through the tenant-scoped repositories in @arayeshgar/core (never raw cross-tenant).
 * Keeping everything keyed by tenant_id is what makes "extract one big customer to their own
 * server" a plain `INSERT INTO ... SELECT ... WHERE tenant_id = X` later.
 *
 * Storage: SQLite (WAL, busy_timeout=5000), per §9ب of PLATFORM.md — the shared backup,
 * `Ops → db-query` and the shared dashboard all assume a `data/*.db` SQLite file.
 *
 * Time: every instant is an INTEGER of whole seconds since the epoch, which is both what
 * drizzle's `{ mode: "timestamp" }` maps to a JS Date and what the dashboard contract reads.
 * Business-day logic is computed in the tenant timezone (default Asia/Tehran, no DST).
 * Weekdays use the Persian week: 0 = Saturday ... 6 = Friday.
 * Money: integer Toman (no decimals).
 * Ids: text holding a UUID v4, generated by the app so inserts never need a round trip.
 */
import { randomUUID } from "node:crypto";
import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  unique,
} from "drizzle-orm/sqlite-core";

// ---------------------------------------------------------------------------
// Enumerations. SQLite has no enum type: these are text columns, typed here and
// enforced by CHECK constraints in the migration.
// ---------------------------------------------------------------------------
export const TENANT_MODES = ["solo", "salon_central", "salon_independent"] as const;
export const TENANT_STATUSES = ["demo", "active", "suspended"] as const;
export const USER_ROLES = ["platform_admin", "owner", "manager", "staff"] as const;
export const PLATFORMS = ["telegram", "bale"] as const;
export const BOOKING_STATUSES = [
  "pending_payment", // deposit enabled: waiting for customer to pay + upload receipt
  "receipt_submitted", // receipt uploaded, waiting for admin review
  "pending_approval", // deposit disabled and auto-confirm off: waiting for admin
  "confirmed",
  "completed",
  "cancelled",
  "rejected", // receipt rejected by admin; slot freed
  "expired", // payment deadline passed; slot freed
  "no_show",
] as const;
export const BOOKING_SOURCES = ["web", "telegram", "bale", "admin"] as const;
export const PAYMENT_STATUSES = ["awaiting_receipt", "submitted", "approved", "rejected"] as const;
export const OVERRIDE_KINDS = ["closed", "open"] as const;
export const ACTOR_TYPES = ["user", "customer", "system"] as const;

/** Column helpers so the same shape is not retyped (and mistyped) on 14 tables. */
const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => randomUUID());
const now = () => sql`(unixepoch())`;
/** Renders a value list for a CHECK. The values are compile-time constants, never input. */
const inList = (values: readonly string[]) => sql.raw(values.map((v) => `'${v}'`).join(", "));

// ---------------------------------------------------------------------------
// JSON shapes (validated with zod in @arayeshgar/core; stored loosely here)
// ---------------------------------------------------------------------------
export type TenantBranding = {
  displayName: string;
  tagline?: string;
  about?: string;
  logoUrl?: string;
  heroImageUrl?: string;
  gallery: string[];
  primaryColor: string;
  accentColor?: string;
  fontHeading: "estedad" | "vazirmatn" | "sahel";
  fontBody: "vazirmatn" | "sahel";
  phone?: string;
  address?: string;
  mapUrl?: string;
  instagram?: string;
  telegram?: string;
  bale?: string;
  faq: { q: string; a: string }[];
  seo?: { title?: string; description?: string };
};

export type TenantFeatures = Record<string, boolean>;

export type BookingRules = {
  slotStepMin: number; // granularity of offered start times (default 15)
  bufferMin: number; // gap after each appointment (default 0)
  minLeadMin: number; // earliest bookable start from now (default 60)
  horizonDays: number; // how far ahead customers can book (default 14)
  paymentDeadlineMin: number; // time to pay deposit before hold expires (default 30)
  cancelBeforeHours: number; // customer self-cancel cutoff (default 4)
  autoConfirmWithoutDeposit: boolean; // default true
  maxActiveBookingsPerPhone: number; // default 1 unpaid hold
  maxBookingsPerPhonePerDay: number; // default 3
};

export type DepositSettings = {
  enabled: boolean;
  cardNumber?: string; // 16 digits, displayed grouped
  cardHolder?: string;
  bankName?: string;
  mode: "fixed" | "percent";
  amount: number; // Toman when fixed, 0-100 when percent
  policyText?: string; // shown to the customer (e.g. deposit forfeited if late cancel)
};

export type StaffDepositSettings = Partial<
  Pick<DepositSettings, "cardNumber" | "cardHolder" | "bankName">
>;

// ---------------------------------------------------------------------------
// Tenants
// ---------------------------------------------------------------------------
export const tenants = sqliteTable(
  "tenants",
  {
    id: id(),
    slug: text("slug").notNull().unique(), // <slug>.<BASE_DOMAIN>
    customDomain: text("custom_domain").unique(),
    name: text("name").notNull(),
    timezone: text("timezone").notNull().default("Asia/Tehran"),
    mode: text("mode", { enum: TENANT_MODES }).notNull().default("solo"),
    status: text("status", { enum: TENANT_STATUSES }).notNull().default("demo"),
    theme: text("theme").notNull().default("night-gold"), // night-gold | light-editorial | bold-modern
    branding: text("branding", { mode: "json" }).$type<TenantBranding>().notNull(),
    features: text("features", { mode: "json" }).$type<TenantFeatures>().notNull().default({}),
    bookingRules: text("booking_rules", { mode: "json" }).$type<BookingRules>().notNull(),
    depositSettings: text("deposit_settings", { mode: "json" }).$type<DepositSettings>().notNull(),
    telegramBotToken: text("telegram_bot_token"),
    telegramBotUsername: text("telegram_bot_username"),
    baleBotToken: text("bale_bot_token"),
    baleBotUsername: text("bale_bot_username"),
    webhookSecret: text("webhook_secret").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("tenants_status_idx").on(t.status),
    check("tenants_mode_ck", sql`${t.mode} IN (${inList(TENANT_MODES)})`),
    check("tenants_status_ck", sql`${t.status} IN (${inList(TENANT_STATUSES)})`),
  ],
);

// ---------------------------------------------------------------------------
// Staff (barbers). Solo tenants have exactly one.
// ---------------------------------------------------------------------------
export const staff = sqliteTable(
  "staff",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    photoUrl: text("photo_url"),
    bio: text("bio"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    // salon_independent: each barber may receive deposits on their own card
    depositSettings: text("deposit_settings", { mode: "json" }).$type<StaffDepositSettings>(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [index("staff_tenant_idx").on(t.tenantId)],
);

// ---------------------------------------------------------------------------
// Users = people who log in to a panel (platform owner, tenant owner/manager/staff)
// ---------------------------------------------------------------------------
export const users = sqliteTable(
  "users",
  {
    id: id(),
    tenantId: text("tenant_id").references(() => tenants.id, { onDelete: "cascade" }), // NULL for platform_admin
    role: text("role", { enum: USER_ROLES }).notNull(),
    staffId: text("staff_id").references(() => staff.id, { onDelete: "set null" }),
    username: text("username").notNull(),
    passwordHash: text("password_hash").notNull(),
    displayName: text("display_name").notNull(),
    telegramChatId: integer("telegram_chat_id"),
    baleChatId: integer("bale_chat_id"),
    botLinkCode: text("bot_link_code"), // one-time code typed into the bot to link a chat
    botLinkCodeExpiresAt: integer("bot_link_code_expires_at", { mode: "timestamp" }),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  // Postgres had NULLS NOT DISTINCT here so two platform admins could not share a
  // username. SQLite always treats NULLs as distinct, so the equivalent index is
  // written by hand over COALESCE(tenant_id,'') in 0001_constraints.sql.
  (t) => [
    index("users_tenant_idx").on(t.tenantId),
    check("users_role_ck", sql`${t.role} IN (${inList(USER_ROLES)})`),
  ],
);

// ---------------------------------------------------------------------------
// Services & prices
// ---------------------------------------------------------------------------
export const services = sqliteTable(
  "services",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    durationMin: integer("duration_min").notNull(),
    price: integer("price").notNull(), // Toman
    sortOrder: integer("sort_order").notNull().default(0),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  },
  (t) => [index("services_tenant_idx").on(t.tenantId)],
);

export const staffServices = sqliteTable(
  "staff_services",
  {
    staffId: text("staff_id")
      .notNull()
      .references(() => staff.id, { onDelete: "cascade" }),
    serviceId: text("service_id")
      .notNull()
      .references(() => services.id, { onDelete: "cascade" }),
    priceOverride: integer("price_override"),
    durationOverrideMin: integer("duration_override_min"),
  },
  (t) => [primaryKey({ columns: [t.staffId, t.serviceId] })],
);

// ---------------------------------------------------------------------------
// Working hours (weekly), overrides (holiday / extra hours), manual slots
// ---------------------------------------------------------------------------
export const schedules = sqliteTable(
  "schedules",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    staffId: text("staff_id")
      .notNull()
      .references(() => staff.id, { onDelete: "cascade" }),
    weekday: integer("weekday").notNull(), // 0 = Saturday ... 6 = Friday
    startMin: integer("start_min").notNull(), // minutes from local midnight
    endMin: integer("end_min").notNull(),
  },
  (t) => [
    unique("schedules_staff_weekday_start_uq").on(t.staffId, t.weekday, t.startMin),
    index("schedules_staff_idx").on(t.staffId),
  ],
);

export const scheduleOverrides = sqliteTable(
  "schedule_overrides",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    staffId: text("staff_id")
      .notNull()
      .references(() => staff.id, { onDelete: "cascade" }),
    day: text("day").notNull(), // local calendar day as YYYY-MM-DD (Gregorian in DB, Jalali in UI)
    kind: text("kind", { enum: OVERRIDE_KINDS }).notNull(),
    startMin: integer("start_min"), // NULL + kind=closed => whole day closed
    endMin: integer("end_min"),
    reason: text("reason"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("schedule_overrides_staff_day_idx").on(t.staffId, t.day),
    check("schedule_overrides_kind_ck", sql`${t.kind} IN (${inList(OVERRIDE_KINDS)})`),
  ],
);

export const manualSlots = sqliteTable(
  "manual_slots",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    staffId: text("staff_id")
      .notNull()
      .references(() => staff.id, { onDelete: "cascade" }),
    startAt: integer("start_at", { mode: "timestamp" }).notNull(),
    endAt: integer("end_at", { mode: "timestamp" }).notNull(),
  },
  (t) => [index("manual_slots_staff_start_idx").on(t.staffId, t.startAt)],
);

// ---------------------------------------------------------------------------
// Customers and their chat identities
// ---------------------------------------------------------------------------
export const customers = sqliteTable(
  "customers",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    phone: text("phone").notNull(), // normalized 09xxxxxxxxx
    notes: text("notes"),
    blocked: integer("blocked", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [unique("customers_tenant_phone_uq").on(t.tenantId, t.phone)],
);

export const customerIdentities = sqliteTable(
  "customer_identities",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    platform: text("platform", { enum: PLATFORMS }).notNull(),
    platformUserId: text("platform_user_id").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    unique("customer_identities_uq").on(t.tenantId, t.platform, t.platformUserId),
    index("customer_identities_customer_idx").on(t.customerId),
    check("customer_identities_platform_ck", sql`${t.platform} IN (${inList(PLATFORMS)})`),
  ],
);

// ---------------------------------------------------------------------------
// Bookings.
//
// Postgres enforced "no two live bookings overlap for one barber" with an EXCLUDE
// constraint. SQLite has none, so the guarantee is rebuilt from two halves that are
// together at least as strong:
//
//   1. Every write goes through BEGIN IMMEDIATE (the default of @libsql/client's
//      transaction()), so a writer takes the single write lock before it reads.
//      Two processes therefore cannot both see the slot free — the second one waits
//      and then reads the first one's committed row.
//   2. `bookings_staff_start_uq`, a partial unique index over (staff_id, start_at)
//      restricted to live statuses, in 0001_constraints.sql. A backstop for the
//      exact-same-start case that holds even if a future caller forgets the lock.
//
// Partial overlap (09:00-09:30 against 09:15-09:45) is caught by the explicit
// overlap query that booking/create.ts runs inside that same transaction.
// ---------------------------------------------------------------------------
export const bookings = sqliteTable(
  "bookings",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    staffId: text("staff_id")
      .notNull()
      .references(() => staff.id, { onDelete: "restrict" }),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "restrict" }),
    serviceId: text("service_id")
      .notNull()
      .references(() => services.id, { onDelete: "restrict" }),
    code: text("code").notNull(), // 6-char human code, unique per tenant
    startAt: integer("start_at", { mode: "timestamp" }).notNull(),
    endAt: integer("end_at", { mode: "timestamp" }).notNull(),
    status: text("status", { enum: BOOKING_STATUSES }).notNull(),
    source: text("source", { enum: BOOKING_SOURCES }).notNull(),
    priceSnapshot: integer("price_snapshot").notNull(),
    depositAmount: integer("deposit_amount").notNull().default(0),
    expiresAt: integer("expires_at", { mode: "timestamp" }), // for pending_payment
    notes: text("notes"),
    cancelledBy: text("cancelled_by"), // 'customer' | 'system' | user id
    cancelReason: text("cancel_reason"),
    reminder24hSentAt: integer("reminder_24h_sent_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    unique("bookings_tenant_code_uq").on(t.tenantId, t.code),
    index("bookings_staff_start_idx").on(t.staffId, t.startAt),
    index("bookings_tenant_start_idx").on(t.tenantId, t.startAt),
    index("bookings_customer_idx").on(t.customerId),
    index("bookings_status_expires_idx").on(t.status, t.expiresAt),
    check("bookings_status_ck", sql`${t.status} IN (${inList(BOOKING_STATUSES)})`),
    check("bookings_source_ck", sql`${t.source} IN (${inList(BOOKING_SOURCES)})`),
    check("bookings_span_ck", sql`${t.endAt} > ${t.startAt}`),
  ],
);

// ---------------------------------------------------------------------------
// Card-to-card deposit payments
// ---------------------------------------------------------------------------
export const payments = sqliteTable(
  "payments",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    bookingId: text("booking_id")
      .notNull()
      .references(() => bookings.id, { onDelete: "cascade" }),
    amount: integer("amount").notNull(),
    status: text("status", { enum: PAYMENT_STATUSES }).notNull().default("awaiting_receipt"),
    // Card the customer was told to pay to (snapshot; staff card in salon_independent)
    payToCardNumber: text("pay_to_card_number"),
    payToCardHolder: text("pay_to_card_holder"),
    receiptPath: text("receipt_path"), // storage key of the uploaded image
    trackingNo: text("tracking_no"),
    submittedAt: integer("submitted_at", { mode: "timestamp" }),
    reviewedBy: text("reviewed_by").references(() => users.id, { onDelete: "set null" }),
    reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
    rejectReason: text("reject_reason"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("payments_booking_idx").on(t.bookingId),
    index("payments_tenant_status_idx").on(t.tenantId, t.status),
    check("payments_status_ck", sql`${t.status} IN (${inList(PAYMENT_STATUSES)})`),
  ],
);

// ---------------------------------------------------------------------------
// Durable notification outbox. SQLite has one writer at a time, so the claim is a
// single conditional UPDATE ... RETURNING instead of FOR UPDATE SKIP LOCKED.
// ---------------------------------------------------------------------------
export const notificationOutbox = sqliteTable(
  "notification_outbox",
  {
    id: id(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    channel: text("channel", { enum: PLATFORMS }).notNull(),
    recipientChatId: text("recipient_chat_id").notNull(),
    kind: text("kind").notNull(), // booking_created | receipt_submitted | ... | reminder_24h
    payload: text("payload", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
    attempts: integer("attempts").notNull().default(0),
    nextTryAt: integer("next_try_at", { mode: "timestamp" }).notNull().default(now()),
    sentAt: integer("sent_at", { mode: "timestamp" }),
    lastError: text("last_error"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("outbox_pending_idx").on(t.sentAt, t.nextTryAt),
    check("outbox_channel_ck", sql`${t.channel} IN (${inList(PLATFORMS)})`),
  ],
);

// ---------------------------------------------------------------------------
// Audit log: who did what (cancel, reschedule, approve receipt, change prices...)
// ---------------------------------------------------------------------------
export const auditLog = sqliteTable(
  "audit_log",
  {
    id: id(),
    tenantId: text("tenant_id").references(() => tenants.id, { onDelete: "cascade" }),
    actorType: text("actor_type", { enum: ACTOR_TYPES }).notNull(),
    actorId: text("actor_id"),
    action: text("action").notNull(),
    entity: text("entity").notNull(),
    entityId: text("entity_id"),
    data: text("data", { mode: "json" }).$type<Record<string, unknown>>(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("audit_tenant_created_idx").on(t.tenantId, t.createdAt),
    check("audit_actor_type_ck", sql`${t.actorType} IN (${inList(ACTOR_TYPES)})`),
  ],
);

// ---------------------------------------------------------------------------
// Bot conversation state (only "awaiting phone" / "awaiting receipt photo"; the rest is
// encoded in callback_data). Persisted so restarts never lose a customer mid-flow.
// ---------------------------------------------------------------------------
export const botSessions = sqliteTable(
  "bot_sessions",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    platform: text("platform", { enum: PLATFORMS }).notNull(),
    platformUserId: text("platform_user_id").notNull(),
    state: text("state", { mode: "json" }).$type<Record<string, unknown>>().notNull().default({}),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.platform, t.platformUserId] }),
    check("bot_sessions_platform_ck", sql`${t.platform} IN (${inList(PLATFORMS)})`),
  ],
);

// ---------------------------------------------------------------------------
// Which barber a chat is currently talking to.
//
// A tenant with its own bot token needs none of this: the token identifies the tenant.
// The shared demo bot is one token serving every prospect at once, so each chat has to
// be remembered, and remembered separately from bot_sessions — that row is deleted the
// moment a flow finishes, and losing the binding with it would drop the customer back
// to "who are you?" right after their first booking.
//
// Keyed by (platform, chat) rather than by tenant: the question being answered is
// "which tenant is this chat's", which cannot be asked of a tenant-scoped table.
// ---------------------------------------------------------------------------
export const botBindings = sqliteTable(
  "bot_bindings",
  {
    platform: text("platform", { enum: PLATFORMS }).notNull(),
    platformUserId: text("platform_user_id").notNull(),
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    primaryKey({ columns: [t.platform, t.platformUserId] }),
    index("bot_bindings_tenant_idx").on(t.tenantId),
    check("bot_bindings_platform_ck", sql`${t.platform} IN (${inList(PLATFORMS)})`),
  ],
);

// ---------------------------------------------------------------------------
// Analytics events — §9ب of PLATFORM.md, contract version 3.
//
// This shape is FIXED. It is identical across every product on the shared server so
// one dashboard can read them all, and §9ب's immutability rule applies: an existing
// event name or prop is never renamed or removed, only added to. `analytics.int.test.ts`
// asserts the emitted DDL still matches the contract, because a silent divergence here
// breaks historical analysis rather than failing loudly.
//
// `user_id` is an INTEGER because the contract assumes a Telegram-first funnel. This
// product is not one: a customer is identified by phone and may never touch a bot. So
// the value is the chat id when the event came from a bot, and a stable negative number
// derived from the customer id when it came from the website — negative so the two can
// never collide, stable so a web customer's events still group together.
//
// Everything tenant-scoped lives in `props`, since the contract has no tenant column.
// ---------------------------------------------------------------------------
export const events = sqliteTable(
  "events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("user_id"),
    event: text("event").notNull(),
    props: text("props", { mode: "json" }).$type<Record<string, unknown>>().notNull().default({}),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now()),
  },
  (t) => [
    index("idx_events_user").on(t.userId, t.createdAt),
    index("idx_events_event").on(t.event, t.createdAt),
  ],
);

export type AnalyticsEvent = typeof events.$inferSelect;

// ---------------------------------------------------------------------------
// Relations (for drizzle relational queries)
// ---------------------------------------------------------------------------
export const tenantsRelations = relations(tenants, ({ many }) => ({
  staff: many(staff),
  users: many(users),
  services: many(services),
  bookings: many(bookings),
}));
export const staffRelations = relations(staff, ({ one, many }) => ({
  tenant: one(tenants, { fields: [staff.tenantId], references: [tenants.id] }),
  schedules: many(schedules),
  staffServices: many(staffServices),
}));
export const servicesRelations = relations(services, ({ one, many }) => ({
  tenant: one(tenants, { fields: [services.tenantId], references: [tenants.id] }),
  staffServices: many(staffServices),
}));
export const staffServicesRelations = relations(staffServices, ({ one }) => ({
  staff: one(staff, { fields: [staffServices.staffId], references: [staff.id] }),
  service: one(services, { fields: [staffServices.serviceId], references: [services.id] }),
}));
export const bookingsRelations = relations(bookings, ({ one, many }) => ({
  tenant: one(tenants, { fields: [bookings.tenantId], references: [tenants.id] }),
  staff: one(staff, { fields: [bookings.staffId], references: [staff.id] }),
  customer: one(customers, { fields: [bookings.customerId], references: [customers.id] }),
  service: one(services, { fields: [bookings.serviceId], references: [services.id] }),
  payments: many(payments),
}));
export const paymentsRelations = relations(payments, ({ one }) => ({
  booking: one(bookings, { fields: [payments.bookingId], references: [bookings.id] }),
}));
export const customersRelations = relations(customers, ({ many }) => ({
  identities: many(customerIdentities),
  bookings: many(bookings),
}));
export const customerIdentitiesRelations = relations(customerIdentities, ({ one }) => ({
  customer: one(customers, { fields: [customerIdentities.customerId], references: [customers.id] }),
}));

// Handy inferred types
export type Tenant = typeof tenants.$inferSelect;
export type NewTenant = typeof tenants.$inferInsert;
export type Staff = typeof staff.$inferSelect;
export type User = typeof users.$inferSelect;
export type Service = typeof services.$inferSelect;
export type Schedule = typeof schedules.$inferSelect;
export type ScheduleOverride = typeof scheduleOverrides.$inferSelect;
export type ManualSlot = typeof manualSlots.$inferSelect;
export type Customer = typeof customers.$inferSelect;
export type Booking = typeof bookings.$inferSelect;
export type NewBooking = typeof bookings.$inferInsert;
export type Payment = typeof payments.$inferSelect;
export type OutboxRow = typeof notificationOutbox.$inferSelect;
export type BookingStatus = (typeof BOOKING_STATUSES)[number];
export type Platform = (typeof PLATFORMS)[number];

// Statuses that keep a slot occupied (mirrors the partial unique index predicate)
export const ACTIVE_BOOKING_STATUSES = [
  "pending_payment",
  "receipt_submitted",
  "pending_approval",
  "confirmed",
  "completed",
] as const satisfies readonly BookingStatus[];

export const activeBookingPredicateSql = sql`status NOT IN ('cancelled','rejected','expired','no_show')`;
